#' Simulation Demo on a right-circular unit cone
#' 
#' Fitting a RFBF from a random data generated by the following parameters 
#' 
#' parameters used to generate random data sets 
#' @param type The manifold considered (a right-circular unit cone) 
#' @param case The shape of the population flow (c, s_short or s_long) 
#'        @example c  A "C"-shaped population flow 
#'        @example s_short  A half of the "S"-shaped population flow
#'        @example s_long  A "S"-shaped population flow
#' @param sd The standard deviation used to generate the noisy data
#' @param R The radius of the right-circular unit cone
#' @param H The height of the right-circular unit cone
#' 
#' parameters used to obtain RFBFs 
#' @param y0 The starting (boundary) point
#' @param y1 The ending (boundary) point
#' @param resolution The number of points on the initial flow connecting 
#' y0 and y1
#' @param h The scale parameter to capture the local variation
#' @param rho The shrinkage constant used during iterations 
#' @param eps The stopping criterion constant 
#' 
#' 
#' @export curve_fbf A RFBF determined by the given parameters and 
#' visualization in 3D space

rm(list=ls())
library(rgl)

# import functions 
source("./RFBF functions/add_functions.R")
source("./RFBF functions/RFBF_smoothing.R")
source("./RFBF functions/RFBF_interpolation.R")
source("./RFBF functions/RFBF_fitting_function.R")

# example begins here
type = "cone"

case = "c" #"s_short" #"s_long"   

sd = 0.015

showcase = paste(type,"_",case,sep="")

if(showcase=="cone_c"){
  # population flow
  pure_curve = data.matrix(read.csv("./data sets/cone_c.csv", header=FALSE))
  # set parameters 
  resolution <- 30
  h <- 0.2
  rho <- 0.95
  eps <- 1e-2
}else if(showcase=="cone_s_short"){
  # population flow
  pure_curve = data.matrix(read.csv("./data sets/cone_s_short.csv", 
                                    header=FALSE))
  # set parameters 
  resolution <- 30
  h <- 0.12
  rho <- 0.95
  eps <- 1e-2
}else if(showcase=="cone_s_long"){
  # population flow
  pure_curve = data.matrix(read.csv("./data sets/cone_s_long.csv", 
                                    header=FALSE))
  # set parameters 
  resolution <- 20
  h <- 0.1
  rho <- 0.95
  eps <- 1e-2
}

cone = data.matrix(read.csv("./data sets/cone.csv", header=FALSE))

n = ncol(pure_curve)

## generate noisy data 
R=1
H=1

manifoldata <- matrix(0,nrow=3,ncol=n)

for (i in 1:n){
  theta_ns <- pi+atan(pure_curve[2,i]/pure_curve[1,i])+rnorm(1,0,sd)
  r_ns <- pure_curve[3,i]*R/H+rnorm(1,0,sd)
  manifoldata[,i] <- c(r_ns*cos(theta_ns),r_ns*sin(theta_ns),H*r_ns/R)
}

# RFBF algorithm begins here

## set boundary points
y0 = pure_curve[,20]
y1 = pure_curve[,ncol(pure_curve)-20]

## initial flow
gamma_ini <- gamma_given(resolution,y0,y1,1)

## Fitting RFBF 
sol <- RFBF_fitting(gamma_ini, manifoldata, y0,y1,h,rho)


## smoothing the flow
sol_smoothing = sol


## interpolation for the flow
dist_min = min(sapply(2:ncol(sol_smoothing),function(ii){norm2(sol_smoothing[,ii]-sol_smoothing[,ii-1])}))
dist_ini = min(norm2(gamma_ini[,2]-gamma_ini[,3]),dist_min)

curve_fbf = FBF_interpolation(sol_smoothing,dist_ini,sphere=FALSE)


## plot the result in 3D
open3d()
points3d(cone[1,],cone[2,],cone[3,],color="yellow",alpha=0.2)
points3d(manifoldata[1,],manifoldata[2,],manifoldata[3,],alpha=0.9)
rgl.spheres(curve_fbf[1,],curve_fbf[2,],curve_fbf[3,], r = 0.005, color = "red")


